// Code generated by MockGen. DO NOT EDIT.
// Source: event_reader.go
//
// Generated by this command:
//
//	mockgen -source event_reader.go -destination=event_reader_mock.go -package=db
//

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockdbConnection is a mock of dbConnection interface.
type MockdbConnection struct {
	ctrl     *gomock.Controller
	recorder *MockdbConnectionMockRecorder
	isgomock struct{}
}

// MockdbConnectionMockRecorder is the mock recorder for MockdbConnection.
type MockdbConnectionMockRecorder struct {
	mock *MockdbConnection
}

// NewMockdbConnection creates a new mock instance.
func NewMockdbConnection(ctrl *gomock.Controller) *MockdbConnection {
	mock := &MockdbConnection{ctrl: ctrl}
	mock.recorder = &MockdbConnectionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbConnection) EXPECT() *MockdbConnectionMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockdbConnection) Query(query string, args ...any) (dbRows, error) {
	m.ctrl.T.Helper()
	varargs := []any{query}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Query", varargs...)
	ret0, _ := ret[0].(dbRows)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockdbConnectionMockRecorder) Query(query any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{query}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockdbConnection)(nil).Query), varargs...)
}

// MockdbRows is a mock of dbRows interface.
type MockdbRows struct {
	ctrl     *gomock.Controller
	recorder *MockdbRowsMockRecorder
	isgomock struct{}
}

// MockdbRowsMockRecorder is the mock recorder for MockdbRows.
type MockdbRowsMockRecorder struct {
	mock *MockdbRows
}

// NewMockdbRows creates a new mock instance.
func NewMockdbRows(ctrl *gomock.Controller) *MockdbRows {
	mock := &MockdbRows{ctrl: ctrl}
	mock.recorder = &MockdbRowsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdbRows) EXPECT() *MockdbRowsMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockdbRows) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockdbRowsMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockdbRows)(nil).Close))
}

// Next mocks base method.
func (m *MockdbRows) Next() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Next")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Next indicates an expected call of Next.
func (mr *MockdbRowsMockRecorder) Next() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Next", reflect.TypeOf((*MockdbRows)(nil).Next))
}

// Scan mocks base method.
func (m *MockdbRows) Scan(dest ...any) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range dest {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Scan", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Scan indicates an expected call of Scan.
func (mr *MockdbRowsMockRecorder) Scan(dest ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scan", reflect.TypeOf((*MockdbRows)(nil).Scan), dest...)
}
