// Code generated by "stringer -type=MessageCode -output message_string.go -trimprefix MessageCode_"; DO NOT EDIT.

package p2p

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MessageCode_UnitTestProtocol_Ping-100]
}

const _MessageCode_name = "UnitTestProtocol_Ping"

var _MessageCode_index = [...]uint8{0, 21}

func (i MessageCode) String() string {
	i -= 100
	if i < 0 || i >= MessageCode(len(_MessageCode_index)-1) {
		return "MessageCode(" + strconv.FormatInt(int64(i+100), 10) + ")"
	}
	return _MessageCode_name[_MessageCode_index[i]:_MessageCode_index[i+1]]
}
