// Code generated by MockGen. DO NOT EDIT.
// Source: network_topology.go
//
// Generated by this command:
//
//	mockgen -source network_topology.go -destination=network_topology_mock.go -package=p2p
//

// Package p2p is a generated GoMock package.
package p2p

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNetworkTopology is a mock of NetworkTopology interface.
type MockNetworkTopology struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkTopologyMockRecorder
	isgomock struct{}
}

// MockNetworkTopologyMockRecorder is the mock recorder for MockNetworkTopology.
type MockNetworkTopologyMockRecorder struct {
	mock *MockNetworkTopology
}

// NewMockNetworkTopology creates a new mock instance.
func NewMockNetworkTopology(ctrl *gomock.Controller) *MockNetworkTopology {
	mock := &MockNetworkTopology{ctrl: ctrl}
	mock.recorder = &MockNetworkTopologyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkTopology) EXPECT() *MockNetworkTopologyMockRecorder {
	return m.recorder
}

// ShouldConnect mocks base method.
func (m *MockNetworkTopology) ShouldConnect(from, to PeerId) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldConnect", from, to)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldConnect indicates an expected call of ShouldConnect.
func (mr *MockNetworkTopologyMockRecorder) ShouldConnect(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldConnect", reflect.TypeOf((*MockNetworkTopology)(nil).ShouldConnect), from, to)
}

// MockTopologyFactory is a mock of TopologyFactory interface.
type MockTopologyFactory struct {
	ctrl     *gomock.Controller
	recorder *MockTopologyFactoryMockRecorder
	isgomock struct{}
}

// MockTopologyFactoryMockRecorder is the mock recorder for MockTopologyFactory.
type MockTopologyFactoryMockRecorder struct {
	mock *MockTopologyFactory
}

// NewMockTopologyFactory creates a new mock instance.
func NewMockTopologyFactory(ctrl *gomock.Controller) *MockTopologyFactory {
	mock := &MockTopologyFactory{ctrl: ctrl}
	mock.recorder = &MockTopologyFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopologyFactory) EXPECT() *MockTopologyFactoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTopologyFactory) Create(peers map[PeerId]int) NetworkTopology {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", peers)
	ret0, _ := ret[0].(NetworkTopology)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTopologyFactoryMockRecorder) Create(peers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTopologyFactory)(nil).Create), peers)
}

// String mocks base method.
func (m *MockTopologyFactory) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockTopologyFactoryMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockTopologyFactory)(nil).String))
}
