// Code generated by MockGen. DO NOT EDIT.
// Source: network_topology.go
//
// Generated by this command:
//
//	mockgen -source network_topology.go -destination=network_topology_mock.go -package=p2p
//

// Package p2p is a generated GoMock package.
package p2p

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockNetworkTopology is a mock of NetworkTopology interface.
type MockNetworkTopology struct {
	ctrl     *gomock.Controller
	recorder *MockNetworkTopologyMockRecorder
	isgomock struct{}
}

// MockNetworkTopologyMockRecorder is the mock recorder for MockNetworkTopology.
type MockNetworkTopologyMockRecorder struct {
	mock *MockNetworkTopology
}

// NewMockNetworkTopology creates a new mock instance.
func NewMockNetworkTopology(ctrl *gomock.Controller) *MockNetworkTopology {
	mock := &MockNetworkTopology{ctrl: ctrl}
	mock.recorder = &MockNetworkTopologyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNetworkTopology) EXPECT() *MockNetworkTopologyMockRecorder {
	return m.recorder
}

// ShouldConnect mocks base method.
func (m *MockNetworkTopology) ShouldConnect(from, to PeerId) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldConnect", from, to)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldConnect indicates an expected call of ShouldConnect.
func (mr *MockNetworkTopologyMockRecorder) ShouldConnect(from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldConnect", reflect.TypeOf((*MockNetworkTopology)(nil).ShouldConnect), from, to)
}
