// Code generated by MockGen. DO NOT EDIT.
// Source: network_delay_model.go
//
// Generated by this command:
//
//	mockgen -source network_delay_model.go -destination=network_delay_model_mock.go -package=p2p
//

// Package p2p is a generated GoMock package.
package p2p

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLatencyModel is a mock of LatencyModel interface.
type MockLatencyModel struct {
	ctrl     *gomock.Controller
	recorder *MockLatencyModelMockRecorder
	isgomock struct{}
}

// MockLatencyModelMockRecorder is the mock recorder for MockLatencyModel.
type MockLatencyModelMockRecorder struct {
	mock *MockLatencyModel
}

// NewMockLatencyModel creates a new mock instance.
func NewMockLatencyModel(ctrl *gomock.Controller) *MockLatencyModel {
	mock := &MockLatencyModel{ctrl: ctrl}
	mock.recorder = &MockLatencyModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLatencyModel) EXPECT() *MockLatencyModelMockRecorder {
	return m.recorder
}

// GetDelay mocks base method.
func (m *MockLatencyModel) GetDelay(from, to PeerId, msg Message) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDelay", from, to, msg)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetDelay indicates an expected call of GetDelay.
func (mr *MockLatencyModelMockRecorder) GetDelay(from, to, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDelay", reflect.TypeOf((*MockLatencyModel)(nil).GetDelay), from, to, msg)
}
