// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source server.go -destination=server_mock.go -package=p2p
//

// Package p2p is a generated GoMock package.
package p2p

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// GetLocalId mocks base method.
func (m *MockServer) GetLocalId() PeerId {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLocalId")
	ret0, _ := ret[0].(PeerId)
	return ret0
}

// GetLocalId indicates an expected call of GetLocalId.
func (mr *MockServerMockRecorder) GetLocalId() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLocalId", reflect.TypeOf((*MockServer)(nil).GetLocalId))
}

// GetPeers mocks base method.
func (m *MockServer) GetPeers() []PeerId {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPeers")
	ret0, _ := ret[0].([]PeerId)
	return ret0
}

// GetPeers indicates an expected call of GetPeers.
func (mr *MockServerMockRecorder) GetPeers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPeers", reflect.TypeOf((*MockServer)(nil).GetPeers))
}

// ReceiveMessage mocks base method.
func (m *MockServer) ReceiveMessage(from PeerId, msg Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReceiveMessage", from, msg)
}

// ReceiveMessage indicates an expected call of ReceiveMessage.
func (mr *MockServerMockRecorder) ReceiveMessage(from, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReceiveMessage", reflect.TypeOf((*MockServer)(nil).ReceiveMessage), from, msg)
}

// RegisterMessageHandler mocks base method.
func (m *MockServer) RegisterMessageHandler(handler MessageHandler) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterMessageHandler", handler)
}

// RegisterMessageHandler indicates an expected call of RegisterMessageHandler.
func (mr *MockServerMockRecorder) RegisterMessageHandler(handler any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterMessageHandler", reflect.TypeOf((*MockServer)(nil).RegisterMessageHandler), handler)
}

// SendMessage mocks base method.
func (m *MockServer) SendMessage(to PeerId, msg Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", to, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockServerMockRecorder) SendMessage(to, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockServer)(nil).SendMessage), to, msg)
}

// MockMessageHandler is a mock of MessageHandler interface.
type MockMessageHandler struct {
	ctrl     *gomock.Controller
	recorder *MockMessageHandlerMockRecorder
	isgomock struct{}
}

// MockMessageHandlerMockRecorder is the mock recorder for MockMessageHandler.
type MockMessageHandlerMockRecorder struct {
	mock *MockMessageHandler
}

// NewMockMessageHandler creates a new mock instance.
func NewMockMessageHandler(ctrl *gomock.Controller) *MockMessageHandler {
	mock := &MockMessageHandler{ctrl: ctrl}
	mock.recorder = &MockMessageHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageHandler) EXPECT() *MockMessageHandlerMockRecorder {
	return m.recorder
}

// HandleMessage mocks base method.
func (m *MockMessageHandler) HandleMessage(from PeerId, msg Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMessage", from, msg)
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockMessageHandlerMockRecorder) HandleMessage(from, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockMessageHandler)(nil).HandleMessage), from, msg)
}
