// Code generated by MockGen. DO NOT EDIT.
// Source: broadcast.go
//
// Generated by this command:
//
//	mockgen -source broadcast.go -destination=broadcast_mock.go -package=generic
//

// Package generic is a generated GoMock package.
package generic

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroadcaster is a mock of Broadcaster interface.
type MockBroadcaster[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcasterMockRecorder[M]
	isgomock struct{}
}

// MockBroadcasterMockRecorder is the mock recorder for MockBroadcaster.
type MockBroadcasterMockRecorder[M any] struct {
	mock *MockBroadcaster[M]
}

// NewMockBroadcaster creates a new mock instance.
func NewMockBroadcaster[M any](ctrl *gomock.Controller) *MockBroadcaster[M] {
	mock := &MockBroadcaster[M]{ctrl: ctrl}
	mock.recorder = &MockBroadcasterMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcaster[M]) EXPECT() *MockBroadcasterMockRecorder[M] {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockBroadcaster[M]) Broadcast(message M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockBroadcasterMockRecorder[M]) Broadcast(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockBroadcaster[M])(nil).Broadcast), message)
}

// RegisterReceiver mocks base method.
func (m *MockBroadcaster[M]) RegisterReceiver(receiver BroadcastReceiver[M]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterReceiver", receiver)
}

// RegisterReceiver indicates an expected call of RegisterReceiver.
func (mr *MockBroadcasterMockRecorder[M]) RegisterReceiver(receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterReceiver", reflect.TypeOf((*MockBroadcaster[M])(nil).RegisterReceiver), receiver)
}

// MockBroadcastReceiver is a mock of BroadcastReceiver interface.
type MockBroadcastReceiver[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockBroadcastReceiverMockRecorder[M]
	isgomock struct{}
}

// MockBroadcastReceiverMockRecorder is the mock recorder for MockBroadcastReceiver.
type MockBroadcastReceiverMockRecorder[M any] struct {
	mock *MockBroadcastReceiver[M]
}

// NewMockBroadcastReceiver creates a new mock instance.
func NewMockBroadcastReceiver[M any](ctrl *gomock.Controller) *MockBroadcastReceiver[M] {
	mock := &MockBroadcastReceiver[M]{ctrl: ctrl}
	mock.recorder = &MockBroadcastReceiverMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroadcastReceiver[M]) EXPECT() *MockBroadcastReceiverMockRecorder[M] {
	return m.recorder
}

// OnMessage mocks base method.
func (m *MockBroadcastReceiver[M]) OnMessage(message M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnMessage", message)
}

// OnMessage indicates an expected call of OnMessage.
func (mr *MockBroadcastReceiverMockRecorder[M]) OnMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMessage", reflect.TypeOf((*MockBroadcastReceiver[M])(nil).OnMessage), message)
}
