// Code generated by MockGen. DO NOT EDIT.
// Source: gossip.go
//
// Generated by this command:
//
//	mockgen -source gossip.go -destination=gossip_mock.go -package=generic
//

// Package generic is a generated GoMock package.
package generic

import (
	reflect "reflect"

	p2p "github.com/0xsoniclabs/daphne/daphne/p2p"
	gomock "go.uber.org/mock/gomock"
)

// MockGossip is a mock of Gossip interface.
type MockGossip[M any] struct {
	ctrl     *gomock.Controller
	recorder *MockGossipMockRecorder[M]
	isgomock struct{}
}

// MockGossipMockRecorder is the mock recorder for MockGossip.
type MockGossipMockRecorder[M any] struct {
	mock *MockGossip[M]
}

// NewMockGossip creates a new mock instance.
func NewMockGossip[M any](ctrl *gomock.Controller) *MockGossip[M] {
	mock := &MockGossip[M]{ctrl: ctrl}
	mock.recorder = &MockGossipMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGossip[M]) EXPECT() *MockGossipMockRecorder[M] {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockGossip[M]) Broadcast(message M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockGossipMockRecorder[M]) Broadcast(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockGossip[M])(nil).Broadcast), message)
}

// HandleMessage mocks base method.
func (m *MockGossip[M]) HandleMessage(from p2p.PeerId, msg p2p.Message) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleMessage", from, msg)
}

// HandleMessage indicates an expected call of HandleMessage.
func (mr *MockGossipMockRecorder[M]) HandleMessage(from, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleMessage", reflect.TypeOf((*MockGossip[M])(nil).HandleMessage), from, msg)
}

// RegisterReceiver mocks base method.
func (m *MockGossip[M]) RegisterReceiver(receiver BroadcastReceiver[M]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterReceiver", receiver)
}

// RegisterReceiver indicates an expected call of RegisterReceiver.
func (mr *MockGossipMockRecorder[M]) RegisterReceiver(receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterReceiver", reflect.TypeOf((*MockGossip[M])(nil).RegisterReceiver), receiver)
}
