// Code generated by MockGen. DO NOT EDIT.
// Source: gossip.go
//
// Generated by this command:
//
//	mockgen -source gossip.go -destination=gossip_mock.go -package=generic
//

// Package generic is a generated GoMock package.
package generic
