// Code generated by MockGen. DO NOT EDIT.
// Source: channel.go
//
// Generated by this command:
//
//	mockgen -source channel.go -destination=channel_mock.go -package=broadcast
//

// Package broadcast is a generated GoMock package.
package broadcast

import (
	reflect "reflect"

	p2p "github.com/0xsoniclabs/daphne/daphne/p2p"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel[M p2p.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder[M]
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder[M p2p.Message] struct {
	mock *MockChannel[M]
}

// NewMockChannel creates a new mock instance.
func NewMockChannel[M p2p.Message](ctrl *gomock.Controller) *MockChannel[M] {
	mock := &MockChannel[M]{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel[M]) EXPECT() *MockChannelMockRecorder[M] {
	return m.recorder
}

// Broadcast mocks base method.
func (m *MockChannel[M]) Broadcast(message M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Broadcast", message)
}

// Broadcast indicates an expected call of Broadcast.
func (mr *MockChannelMockRecorder[M]) Broadcast(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Broadcast", reflect.TypeOf((*MockChannel[M])(nil).Broadcast), message)
}

// Register mocks base method.
func (m *MockChannel[M]) Register(receiver Receiver[M]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Register", receiver)
}

// Register indicates an expected call of Register.
func (mr *MockChannelMockRecorder[M]) Register(receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockChannel[M])(nil).Register), receiver)
}

// Unregister mocks base method.
func (m *MockChannel[M]) Unregister(receiver Receiver[M]) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unregister", receiver)
}

// Unregister indicates an expected call of Unregister.
func (mr *MockChannelMockRecorder[M]) Unregister(receiver any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unregister", reflect.TypeOf((*MockChannel[M])(nil).Unregister), receiver)
}

// MockReceiver is a mock of Receiver interface.
type MockReceiver[M p2p.Message] struct {
	ctrl     *gomock.Controller
	recorder *MockReceiverMockRecorder[M]
	isgomock struct{}
}

// MockReceiverMockRecorder is the mock recorder for MockReceiver.
type MockReceiverMockRecorder[M p2p.Message] struct {
	mock *MockReceiver[M]
}

// NewMockReceiver creates a new mock instance.
func NewMockReceiver[M p2p.Message](ctrl *gomock.Controller) *MockReceiver[M] {
	mock := &MockReceiver[M]{ctrl: ctrl}
	mock.recorder = &MockReceiverMockRecorder[M]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiver[M]) EXPECT() *MockReceiverMockRecorder[M] {
	return m.recorder
}

// OnMessage mocks base method.
func (m *MockReceiver[M]) OnMessage(message M) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnMessage", message)
}

// OnMessage indicates an expected call of OnMessage.
func (mr *MockReceiverMockRecorder[M]) OnMessage(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnMessage", reflect.TypeOf((*MockReceiver[M])(nil).OnMessage), message)
}
