// Code generated by MockGen. DO NOT EDIT.
// Source: gossip_strategy.go
//
// Generated by this command:
//
//	mockgen -source gossip_strategy.go -destination=gossip_strategy_mock.go -package=broadcast
//

// Package broadcast is a generated GoMock package.
package broadcast

import (
	reflect "reflect"

	p2p "github.com/0xsoniclabs/daphne/daphne/p2p"
	gomock "go.uber.org/mock/gomock"
)

// MockGossipStrategy is a mock of GossipStrategy interface.
type MockGossipStrategy[K comparable] struct {
	ctrl     *gomock.Controller
	recorder *MockGossipStrategyMockRecorder[K]
	isgomock struct{}
}

// MockGossipStrategyMockRecorder is the mock recorder for MockGossipStrategy.
type MockGossipStrategyMockRecorder[K comparable] struct {
	mock *MockGossipStrategy[K]
}

// NewMockGossipStrategy creates a new mock instance.
func NewMockGossipStrategy[K comparable](ctrl *gomock.Controller) *MockGossipStrategy[K] {
	mock := &MockGossipStrategy[K]{ctrl: ctrl}
	mock.recorder = &MockGossipStrategyMockRecorder[K]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGossipStrategy[K]) EXPECT() *MockGossipStrategyMockRecorder[K] {
	return m.recorder
}

// OnReceived mocks base method.
func (m *MockGossipStrategy[K]) OnReceived(peer p2p.PeerId, messageKey K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnReceived", peer, messageKey)
}

// OnReceived indicates an expected call of OnReceived.
func (mr *MockGossipStrategyMockRecorder[K]) OnReceived(peer, messageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnReceived", reflect.TypeOf((*MockGossipStrategy[K])(nil).OnReceived), peer, messageKey)
}

// OnSendFailed mocks base method.
func (m *MockGossipStrategy[K]) OnSendFailed(peer p2p.PeerId, messageKey K, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSendFailed", peer, messageKey, err)
}

// OnSendFailed indicates an expected call of OnSendFailed.
func (mr *MockGossipStrategyMockRecorder[K]) OnSendFailed(peer, messageKey, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSendFailed", reflect.TypeOf((*MockGossipStrategy[K])(nil).OnSendFailed), peer, messageKey, err)
}

// OnSent mocks base method.
func (m *MockGossipStrategy[K]) OnSent(peer p2p.PeerId, messageKey K) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSent", peer, messageKey)
}

// OnSent indicates an expected call of OnSent.
func (mr *MockGossipStrategyMockRecorder[K]) OnSent(peer, messageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSent", reflect.TypeOf((*MockGossipStrategy[K])(nil).OnSent), peer, messageKey)
}

// ShouldGossip mocks base method.
func (m *MockGossipStrategy[K]) ShouldGossip(peer p2p.PeerId, messageKey K) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldGossip", peer, messageKey)
	ret0, _ := ret[0].(bool)
	return ret0
}

// ShouldGossip indicates an expected call of ShouldGossip.
func (mr *MockGossipStrategyMockRecorder[K]) ShouldGossip(peer, messageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldGossip", reflect.TypeOf((*MockGossipStrategy[K])(nil).ShouldGossip), peer, messageKey)
}
