// Code generated by "stringer -type=Protocol -output protocols_string.go -trimprefix Protocol"; DO NOT EDIT.

package broadcast

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ProtocolGossip-0]
	_ = x[ProtocolForwarding-1]
}

const _Protocol_name = "GossipForwarding"

var _Protocol_index = [...]uint8{0, 6, 16}

func (i Protocol) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_Protocol_index)-1 {
		return "Protocol(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Protocol_name[_Protocol_index[idx]:_Protocol_index[idx+1]]
}
