# Copyright 2026 Sonic Operations Ltd
# This file is part of the Daphne consensus development infrastructure for Sonic.
#
# Daphne is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Daphne is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with Daphne. If not, see <http://www.gnu.org/licenses/>.

# default coverage setting
coverage:
  range: 90..99 # below 90 is red, between 90-99 is yellow and above 99 is green
  round: down
  precision: 2
  status:
    patch:
      default:
        target: 100% # coverage of the changes
    project:
      default:
        target: 100% # coverage of the project

ignore:
  - "tests/"
  - "**/*_mock.go"
  - "**/*_test.go"
  - "**/*.pb.go"
  - "**/*_string.go"
  # ignore license header check script for coverage
  - "scripts/license/add_license_header.go"
