// Code generated by MockGen. DO NOT EDIT.
// Source: delay_model.go
//
// Generated by this command:
//
//	mockgen -source delay_model.go -destination=delay_model_mock.go -package=utils
//

// Package utils is a generated GoMock package.
package utils

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockDistribution is a mock of Distribution interface.
type MockDistribution struct {
	ctrl     *gomock.Controller
	recorder *MockDistributionMockRecorder
	isgomock struct{}
}

// MockDistributionMockRecorder is the mock recorder for MockDistribution.
type MockDistributionMockRecorder struct {
	mock *MockDistribution
}

// NewMockDistribution creates a new mock instance.
func NewMockDistribution(ctrl *gomock.Controller) *MockDistribution {
	mock := &MockDistribution{ctrl: ctrl}
	mock.recorder = &MockDistributionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDistribution) EXPECT() *MockDistributionMockRecorder {
	return m.recorder
}

// Quantile mocks base method.
func (m *MockDistribution) Quantile(probability float64) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quantile", probability)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// Quantile indicates an expected call of Quantile.
func (mr *MockDistributionMockRecorder) Quantile(probability any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quantile", reflect.TypeOf((*MockDistribution)(nil).Quantile), probability)
}

// SampleDuration mocks base method.
func (m *MockDistribution) SampleDuration() time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleDuration")
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// SampleDuration indicates an expected call of SampleDuration.
func (mr *MockDistributionMockRecorder) SampleDuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleDuration", reflect.TypeOf((*MockDistribution)(nil).SampleDuration))
}
