// Code generated by MockGen. DO NOT EDIT.
// Source: lineup.go
//
// Generated by this command:
//
//	mockgen -source lineup.go -destination=lineup_mock.go -package=txpool
//

// Package txpool is a generated GoMock package.
package txpool

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockLineup is a mock of Lineup interface.
type MockLineup struct {
	ctrl     *gomock.Controller
	recorder *MockLineupMockRecorder
	isgomock struct{}
}

// MockLineupMockRecorder is the mock recorder for MockLineup.
type MockLineupMockRecorder struct {
	mock *MockLineup
}

// NewMockLineup creates a new mock instance.
func NewMockLineup(ctrl *gomock.Controller) *MockLineup {
	mock := &MockLineup{ctrl: ctrl}
	mock.recorder = &MockLineupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineup) EXPECT() *MockLineupMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockLineup) Consume(arg0 LineupFilter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Consume", arg0)
}

// Consume indicates an expected call of Consume.
func (mr *MockLineupMockRecorder) Consume(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockLineup)(nil).Consume), arg0)
}

// MockLineupConsumer is a mock of LineupConsumer interface.
type MockLineupConsumer struct {
	ctrl     *gomock.Controller
	recorder *MockLineupConsumerMockRecorder
	isgomock struct{}
}

// MockLineupConsumerMockRecorder is the mock recorder for MockLineupConsumer.
type MockLineupConsumerMockRecorder struct {
	mock *MockLineupConsumer
}

// NewMockLineupConsumer creates a new mock instance.
func NewMockLineupConsumer(ctrl *gomock.Controller) *MockLineupConsumer {
	mock := &MockLineupConsumer{ctrl: ctrl}
	mock.recorder = &MockLineupConsumerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineupConsumer) EXPECT() *MockLineupConsumerMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockLineupConsumer) Process(arg0 types.Transaction) LineupDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", arg0)
	ret0, _ := ret[0].(LineupDecision)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockLineupConsumerMockRecorder) Process(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockLineupConsumer)(nil).Process), arg0)
}
