// Code generated by "stringer -type=LineupDecision -output lineup_string.go -trimprefix Lineup"; DO NOT EDIT.

package txpool

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LineupAccept-0]
	_ = x[LineupReject-1]
	_ = x[LineupAbort-2]
}

const _LineupDecision_name = "AcceptRejectAbort"

var _LineupDecision_index = [...]uint8{0, 6, 12, 17}

func (i LineupDecision) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_LineupDecision_index)-1 {
		return "LineupDecision(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LineupDecision_name[_LineupDecision_index[idx]:_LineupDecision_index[idx+1]]
}
