// Code generated by MockGen. DO NOT EDIT.
// Source: lineup.go
//
// Generated by this command:
//
//	mockgen -source lineup.go -destination=lineup_mock.go -package=txpool
//

// Package txpool is a generated GoMock package.
package txpool

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockLineup is a mock of Lineup interface.
type MockLineup struct {
	ctrl     *gomock.Controller
	recorder *MockLineupMockRecorder
	isgomock struct{}
}

// MockLineupMockRecorder is the mock recorder for MockLineup.
type MockLineupMockRecorder struct {
	mock *MockLineup
}

// NewMockLineup creates a new mock instance.
func NewMockLineup(ctrl *gomock.Controller) *MockLineup {
	mock := &MockLineup{ctrl: ctrl}
	mock.recorder = &MockLineupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineup) EXPECT() *MockLineupMockRecorder {
	return m.recorder
}

// Process mocks base method.
func (m *MockLineup) Process(arg0 LineupFilter) []types.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Process", arg0)
	ret0, _ := ret[0].([]types.Transaction)
	return ret0
}

// Process indicates an expected call of Process.
func (mr *MockLineupMockRecorder) Process(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockLineup)(nil).Process), arg0)
}

// MockLineupFilter is a mock of LineupFilter interface.
type MockLineupFilter struct {
	ctrl     *gomock.Controller
	recorder *MockLineupFilterMockRecorder
	isgomock struct{}
}

// MockLineupFilterMockRecorder is the mock recorder for MockLineupFilter.
type MockLineupFilterMockRecorder struct {
	mock *MockLineupFilter
}

// NewMockLineupFilter creates a new mock instance.
func NewMockLineupFilter(ctrl *gomock.Controller) *MockLineupFilter {
	mock := &MockLineupFilter{ctrl: ctrl}
	mock.recorder = &MockLineupFilterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineupFilter) EXPECT() *MockLineupFilterMockRecorder {
	return m.recorder
}

// Filter mocks base method.
func (m *MockLineupFilter) Filter(arg0 types.Transaction) LineupDecision {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Filter", arg0)
	ret0, _ := ret[0].(LineupDecision)
	return ret0
}

// Filter indicates an expected call of Filter.
func (mr *MockLineupFilterMockRecorder) Filter(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Filter", reflect.TypeOf((*MockLineupFilter)(nil).Filter), arg0)
}
