// Code generated by MockGen. DO NOT EDIT.
// Source: txpool.go
//
// Generated by this command:
//
//	mockgen -source txpool.go -destination=txpool_mock.go -package=txpool
//

// Package txpool is a generated GoMock package.
package txpool

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTxPool is a mock of TxPool interface.
type MockTxPool struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolMockRecorder
	isgomock struct{}
}

// MockTxPoolMockRecorder is the mock recorder for MockTxPool.
type MockTxPoolMockRecorder struct {
	mock *MockTxPool
}

// NewMockTxPool creates a new mock instance.
func NewMockTxPool(ctrl *gomock.Controller) *MockTxPool {
	mock := &MockTxPool{ctrl: ctrl}
	mock.recorder = &MockTxPoolMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPool) EXPECT() *MockTxPoolMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockTxPool) Add(tx types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockTxPoolMockRecorder) Add(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockTxPool)(nil).Add), tx)
}

// GetExecutableTransactions mocks base method.
func (m *MockTxPool) GetExecutableTransactions(arg0 NonceSource) []types.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExecutableTransactions", arg0)
	ret0, _ := ret[0].([]types.Transaction)
	return ret0
}

// GetExecutableTransactions indicates an expected call of GetExecutableTransactions.
func (mr *MockTxPoolMockRecorder) GetExecutableTransactions(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExecutableTransactions", reflect.TypeOf((*MockTxPool)(nil).GetExecutableTransactions), arg0)
}

// RegisterListener mocks base method.
func (m *MockTxPool) RegisterListener(arg0 TxPoolListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterListener", arg0)
}

// RegisterListener indicates an expected call of RegisterListener.
func (mr *MockTxPoolMockRecorder) RegisterListener(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterListener", reflect.TypeOf((*MockTxPool)(nil).RegisterListener), arg0)
}

// MockNonceSource is a mock of NonceSource interface.
type MockNonceSource struct {
	ctrl     *gomock.Controller
	recorder *MockNonceSourceMockRecorder
	isgomock struct{}
}

// MockNonceSourceMockRecorder is the mock recorder for MockNonceSource.
type MockNonceSourceMockRecorder struct {
	mock *MockNonceSource
}

// NewMockNonceSource creates a new mock instance.
func NewMockNonceSource(ctrl *gomock.Controller) *MockNonceSource {
	mock := &MockNonceSource{ctrl: ctrl}
	mock.recorder = &MockNonceSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNonceSource) EXPECT() *MockNonceSourceMockRecorder {
	return m.recorder
}

// GetNonce mocks base method.
func (m *MockNonceSource) GetNonce(address types.Address) types.Nonce {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNonce", address)
	ret0, _ := ret[0].(types.Nonce)
	return ret0
}

// GetNonce indicates an expected call of GetNonce.
func (mr *MockNonceSourceMockRecorder) GetNonce(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNonce", reflect.TypeOf((*MockNonceSource)(nil).GetNonce), address)
}

// MockTxPoolListener is a mock of TxPoolListener interface.
type MockTxPoolListener struct {
	ctrl     *gomock.Controller
	recorder *MockTxPoolListenerMockRecorder
	isgomock struct{}
}

// MockTxPoolListenerMockRecorder is the mock recorder for MockTxPoolListener.
type MockTxPoolListenerMockRecorder struct {
	mock *MockTxPoolListener
}

// NewMockTxPoolListener creates a new mock instance.
func NewMockTxPoolListener(ctrl *gomock.Controller) *MockTxPoolListener {
	mock := &MockTxPoolListener{ctrl: ctrl}
	mock.recorder = &MockTxPoolListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxPoolListener) EXPECT() *MockTxPoolListenerMockRecorder {
	return m.recorder
}

// OnNewTransaction mocks base method.
func (m *MockTxPoolListener) OnNewTransaction(tx types.Transaction) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNewTransaction", tx)
}

// OnNewTransaction indicates an expected call of OnNewTransaction.
func (mr *MockTxPoolListenerMockRecorder) OnNewTransaction(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNewTransaction", reflect.TypeOf((*MockTxPoolListener)(nil).OnNewTransaction), tx)
}
