// Code generated by MockGen. DO NOT EDIT.
// Source: consensus.go
//
// Generated by this command:
//
//	mockgen -source consensus.go -destination=consensus_mock.go -package=consensus
//

// Package consensus is a generated GoMock package.
package consensus

import (
	reflect "reflect"

	p2p "github.com/0xsoniclabs/daphne/daphne/p2p"
	txpool "github.com/0xsoniclabs/daphne/daphne/txpool"
	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockConsensus is a mock of Consensus interface.
type MockConsensus struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusMockRecorder
	isgomock struct{}
}

// MockConsensusMockRecorder is the mock recorder for MockConsensus.
type MockConsensusMockRecorder struct {
	mock *MockConsensus
}

// NewMockConsensus creates a new mock instance.
func NewMockConsensus(ctrl *gomock.Controller) *MockConsensus {
	mock := &MockConsensus{ctrl: ctrl}
	mock.recorder = &MockConsensusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensus) EXPECT() *MockConsensusMockRecorder {
	return m.recorder
}

// RegisterListener mocks base method.
func (m *MockConsensus) RegisterListener(listener BundleListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterListener", listener)
}

// RegisterListener indicates an expected call of RegisterListener.
func (mr *MockConsensusMockRecorder) RegisterListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterListener", reflect.TypeOf((*MockConsensus)(nil).RegisterListener), listener)
}

// Stop mocks base method.
func (m *MockConsensus) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockConsensusMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockConsensus)(nil).Stop))
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewActive mocks base method.
func (m *MockFactory) NewActive(arg0 p2p.Server, arg1 Committee, arg2 ValidatorId, arg3 TransactionProvider) Consensus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewActive", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(Consensus)
	return ret0
}

// NewActive indicates an expected call of NewActive.
func (mr *MockFactoryMockRecorder) NewActive(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewActive", reflect.TypeOf((*MockFactory)(nil).NewActive), arg0, arg1, arg2, arg3)
}

// NewPassive mocks base method.
func (m *MockFactory) NewPassive(arg0 p2p.Server, arg1 Committee) Consensus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPassive", arg0, arg1)
	ret0, _ := ret[0].(Consensus)
	return ret0
}

// NewPassive indicates an expected call of NewPassive.
func (mr *MockFactoryMockRecorder) NewPassive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPassive", reflect.TypeOf((*MockFactory)(nil).NewPassive), arg0, arg1)
}

// String mocks base method.
func (m *MockFactory) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockFactoryMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockFactory)(nil).String))
}

// MockTransactionProvider is a mock of TransactionProvider interface.
type MockTransactionProvider struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionProviderMockRecorder
	isgomock struct{}
}

// MockTransactionProviderMockRecorder is the mock recorder for MockTransactionProvider.
type MockTransactionProviderMockRecorder struct {
	mock *MockTransactionProvider
}

// NewMockTransactionProvider creates a new mock instance.
func NewMockTransactionProvider(ctrl *gomock.Controller) *MockTransactionProvider {
	mock := &MockTransactionProvider{ctrl: ctrl}
	mock.recorder = &MockTransactionProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionProvider) EXPECT() *MockTransactionProviderMockRecorder {
	return m.recorder
}

// GetCandidateLineup mocks base method.
func (m *MockTransactionProvider) GetCandidateLineup() txpool.Lineup {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidateLineup")
	ret0, _ := ret[0].(txpool.Lineup)
	return ret0
}

// GetCandidateLineup indicates an expected call of GetCandidateLineup.
func (mr *MockTransactionProviderMockRecorder) GetCandidateLineup() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidateLineup", reflect.TypeOf((*MockTransactionProvider)(nil).GetCandidateLineup))
}

// MockBundleListener is a mock of BundleListener interface.
type MockBundleListener struct {
	ctrl     *gomock.Controller
	recorder *MockBundleListenerMockRecorder
	isgomock struct{}
}

// MockBundleListenerMockRecorder is the mock recorder for MockBundleListener.
type MockBundleListenerMockRecorder struct {
	mock *MockBundleListener
}

// NewMockBundleListener creates a new mock instance.
func NewMockBundleListener(ctrl *gomock.Controller) *MockBundleListener {
	mock := &MockBundleListener{ctrl: ctrl}
	mock.recorder = &MockBundleListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleListener) EXPECT() *MockBundleListenerMockRecorder {
	return m.recorder
}

// OnNewBundle mocks base method.
func (m *MockBundleListener) OnNewBundle(bundle types.Bundle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNewBundle", bundle)
}

// OnNewBundle indicates an expected call of OnNewBundle.
func (mr *MockBundleListenerMockRecorder) OnNewBundle(bundle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNewBundle", reflect.TypeOf((*MockBundleListener)(nil).OnNewBundle), bundle)
}
