// Code generated by MockGen. DO NOT EDIT.
// Source: consensus.go
//
// Generated by this command:
//
//	mockgen -source consensus.go -destination=consensus_mock.go -package=consensus
//

// Package consensus is a generated GoMock package.
package consensus

import (
	reflect "reflect"

	p2p "github.com/0xsoniclabs/daphne/daphne/p2p"
	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockAlgorithm is a mock of Algorithm interface.
type MockAlgorithm struct {
	ctrl     *gomock.Controller
	recorder *MockAlgorithmMockRecorder
	isgomock struct{}
}

// MockAlgorithmMockRecorder is the mock recorder for MockAlgorithm.
type MockAlgorithmMockRecorder struct {
	mock *MockAlgorithm
}

// NewMockAlgorithm creates a new mock instance.
func NewMockAlgorithm(ctrl *gomock.Controller) *MockAlgorithm {
	mock := &MockAlgorithm{ctrl: ctrl}
	mock.recorder = &MockAlgorithmMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAlgorithm) EXPECT() *MockAlgorithmMockRecorder {
	return m.recorder
}

// NewActive mocks base method.
func (m *MockAlgorithm) NewActive(arg0 p2p.Server, arg1 PayloadSource) Consensus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewActive", arg0, arg1)
	ret0, _ := ret[0].(Consensus)
	return ret0
}

// NewActive indicates an expected call of NewActive.
func (mr *MockAlgorithmMockRecorder) NewActive(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewActive", reflect.TypeOf((*MockAlgorithm)(nil).NewActive), arg0, arg1)
}

// NewPassive mocks base method.
func (m *MockAlgorithm) NewPassive(arg0 p2p.Server) Consensus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewPassive", arg0)
	ret0, _ := ret[0].(Consensus)
	return ret0
}

// NewPassive indicates an expected call of NewPassive.
func (mr *MockAlgorithmMockRecorder) NewPassive(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewPassive", reflect.TypeOf((*MockAlgorithm)(nil).NewPassive), arg0)
}

// MockPayloadSource is a mock of PayloadSource interface.
type MockPayloadSource struct {
	ctrl     *gomock.Controller
	recorder *MockPayloadSourceMockRecorder
	isgomock struct{}
}

// MockPayloadSourceMockRecorder is the mock recorder for MockPayloadSource.
type MockPayloadSourceMockRecorder struct {
	mock *MockPayloadSource
}

// NewMockPayloadSource creates a new mock instance.
func NewMockPayloadSource(ctrl *gomock.Controller) *MockPayloadSource {
	mock := &MockPayloadSource{ctrl: ctrl}
	mock.recorder = &MockPayloadSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayloadSource) EXPECT() *MockPayloadSourceMockRecorder {
	return m.recorder
}

// GetCandidateTransactions mocks base method.
func (m *MockPayloadSource) GetCandidateTransactions() []types.Transaction {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCandidateTransactions")
	ret0, _ := ret[0].([]types.Transaction)
	return ret0
}

// GetCandidateTransactions indicates an expected call of GetCandidateTransactions.
func (mr *MockPayloadSourceMockRecorder) GetCandidateTransactions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCandidateTransactions", reflect.TypeOf((*MockPayloadSource)(nil).GetCandidateTransactions))
}

// MockConsensus is a mock of Consensus interface.
type MockConsensus struct {
	ctrl     *gomock.Controller
	recorder *MockConsensusMockRecorder
	isgomock struct{}
}

// MockConsensusMockRecorder is the mock recorder for MockConsensus.
type MockConsensusMockRecorder struct {
	mock *MockConsensus
}

// NewMockConsensus creates a new mock instance.
func NewMockConsensus(ctrl *gomock.Controller) *MockConsensus {
	mock := &MockConsensus{ctrl: ctrl}
	mock.recorder = &MockConsensusMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConsensus) EXPECT() *MockConsensusMockRecorder {
	return m.recorder
}

// RegisterListener mocks base method.
func (m *MockConsensus) RegisterListener(listener BundleListener) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterListener", listener)
}

// RegisterListener indicates an expected call of RegisterListener.
func (mr *MockConsensusMockRecorder) RegisterListener(listener any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterListener", reflect.TypeOf((*MockConsensus)(nil).RegisterListener), listener)
}

// MockBundleListener is a mock of BundleListener interface.
type MockBundleListener struct {
	ctrl     *gomock.Controller
	recorder *MockBundleListenerMockRecorder
	isgomock struct{}
}

// MockBundleListenerMockRecorder is the mock recorder for MockBundleListener.
type MockBundleListenerMockRecorder struct {
	mock *MockBundleListener
}

// NewMockBundleListener creates a new mock instance.
func NewMockBundleListener(ctrl *gomock.Controller) *MockBundleListener {
	mock := &MockBundleListener{ctrl: ctrl}
	mock.recorder = &MockBundleListenerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBundleListener) EXPECT() *MockBundleListenerMockRecorder {
	return m.recorder
}

// OnNewBundle mocks base method.
func (m *MockBundleListener) OnNewBundle(bundle types.Bundle) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnNewBundle", bundle)
}

// OnNewBundle indicates an expected call of OnNewBundle.
func (mr *MockBundleListenerMockRecorder) OnNewBundle(bundle any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnNewBundle", reflect.TypeOf((*MockBundleListener)(nil).OnNewBundle), bundle)
}
