// Code generated by MockGen. DO NOT EDIT.
// Source: receipt_store.go
//
// Generated by this command:
//
//	mockgen -source receipt_store.go -destination=receipt_store_mock.go -package=rpc
//

// Package rpc is a generated GoMock package.
package rpc

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockReceiptStore is a mock of ReceiptStore interface.
type MockReceiptStore struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptStoreMockRecorder
	isgomock struct{}
}

// MockReceiptStoreMockRecorder is the mock recorder for MockReceiptStore.
type MockReceiptStoreMockRecorder struct {
	mock *MockReceiptStore
}

// NewMockReceiptStore creates a new mock instance.
func NewMockReceiptStore(ctrl *gomock.Controller) *MockReceiptStore {
	mock := &MockReceiptStore{ctrl: ctrl}
	mock.recorder = &MockReceiptStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptStore) EXPECT() *MockReceiptStoreMockRecorder {
	return m.recorder
}

// AddBlock mocks base method.
func (m *MockReceiptStore) AddBlock(block types.Block) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBlock", block)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBlock indicates an expected call of AddBlock.
func (mr *MockReceiptStoreMockRecorder) AddBlock(block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlock", reflect.TypeOf((*MockReceiptStore)(nil).AddBlock), block)
}

// GetReceipt mocks base method.
func (m *MockReceiptStore) GetReceipt(txHash types.Hash) (types.Receipt, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipt", txHash)
	ret0, _ := ret[0].(types.Receipt)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetReceipt indicates an expected call of GetReceipt.
func (mr *MockReceiptStoreMockRecorder) GetReceipt(txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipt", reflect.TypeOf((*MockReceiptStore)(nil).GetReceipt), txHash)
}
