// Code generated by MockGen. DO NOT EDIT.
// Source: protocol.go
//
// Generated by this command:
//
//	mockgen -source protocol.go -destination=protocol_mock.go -package=payload
//

// Package payload is a generated GoMock package.
package payload

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProtocol is a mock of Protocol interface.
type MockProtocol[P Payload] struct {
	ctrl     *gomock.Controller
	recorder *MockProtocolMockRecorder[P]
	isgomock struct{}
}

// MockProtocolMockRecorder is the mock recorder for MockProtocol.
type MockProtocolMockRecorder[P Payload] struct {
	mock *MockProtocol[P]
}

// NewMockProtocol creates a new mock instance.
func NewMockProtocol[P Payload](ctrl *gomock.Controller) *MockProtocol[P] {
	mock := &MockProtocol[P]{ctrl: ctrl}
	mock.recorder = &MockProtocolMockRecorder[P]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProtocol[P]) EXPECT() *MockProtocolMockRecorder[P] {
	return m.recorder
}

// BuildPayload mocks base method.
func (m *MockProtocol[P]) BuildPayload(candidates []types.Transaction) P {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildPayload", candidates)
	ret0, _ := ret[0].(P)
	return ret0
}

// BuildPayload indicates an expected call of BuildPayload.
func (mr *MockProtocolMockRecorder[P]) BuildPayload(candidates any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildPayload", reflect.TypeOf((*MockProtocol[P])(nil).BuildPayload), candidates)
}

// Merge mocks base method.
func (m *MockProtocol[P]) Merge(payloads []P) []types.Bundle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", payloads)
	ret0, _ := ret[0].([]types.Bundle)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockProtocolMockRecorder[P]) Merge(payloads any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockProtocol[P])(nil).Merge), payloads)
}

// String mocks base method.
func (m *MockProtocol[P]) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockProtocolMockRecorder[P]) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockProtocol[P])(nil).String))
}
