// Code generated by "stringer -type=Mark -output marks_string.go"; DO NOT EDIT.

package mark

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MsgSent-0]
	_ = x[MsgReceived-1]
	_ = x[MsgConsumed-2]
	_ = x[TxSubmitted-3]
	_ = x[TxAddedToPool-4]
	_ = x[TxConfirmed-5]
	_ = x[TxBeginProcessing-6]
	_ = x[TxEndProcessing-7]
	_ = x[TxSkipped-8]
	_ = x[TxFinalized-9]
}

const _Mark_name = "MsgSentMsgReceivedMsgConsumedTxSubmittedTxAddedToPoolTxConfirmedTxBeginProcessingTxEndProcessingTxSkippedTxFinalized"

var _Mark_index = [...]uint8{0, 7, 18, 29, 40, 53, 64, 81, 96, 105, 116}

func (i Mark) String() string {
	if i < 0 || i >= Mark(len(_Mark_index)-1) {
		return "Mark(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mark_name[_Mark_index[i]:_Mark_index[i+1]]
}
