// Code generated by MockGen. DO NOT EDIT.
// Source: emitter.go
//
// Generated by this command:
//
//	mockgen -source emitter.go -destination=emitter_mock.go -package=emitter
//

// Package emitter is a generated GoMock package.
package emitter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmissionPayloadSource is a mock of EmissionPayloadSource interface.
type MockEmissionPayloadSource[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEmissionPayloadSourceMockRecorder[T]
	isgomock struct{}
}

// MockEmissionPayloadSourceMockRecorder is the mock recorder for MockEmissionPayloadSource.
type MockEmissionPayloadSourceMockRecorder[T any] struct {
	mock *MockEmissionPayloadSource[T]
}

// NewMockEmissionPayloadSource creates a new mock instance.
func NewMockEmissionPayloadSource[T any](ctrl *gomock.Controller) *MockEmissionPayloadSource[T] {
	mock := &MockEmissionPayloadSource[T]{ctrl: ctrl}
	mock.recorder = &MockEmissionPayloadSourceMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmissionPayloadSource[T]) EXPECT() *MockEmissionPayloadSourceMockRecorder[T] {
	return m.recorder
}

// GetEmissionPayload mocks base method.
func (m *MockEmissionPayloadSource[T]) GetEmissionPayload() T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEmissionPayload")
	ret0, _ := ret[0].(T)
	return ret0
}

// GetEmissionPayload indicates an expected call of GetEmissionPayload.
func (mr *MockEmissionPayloadSourceMockRecorder[T]) GetEmissionPayload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEmissionPayload", reflect.TypeOf((*MockEmissionPayloadSource[T])(nil).GetEmissionPayload))
}
