// Code generated by MockGen. DO NOT EDIT.
// Source: dag.go
//
// Generated by this command:
//
//	mockgen -source dag.go -destination=dag_mock.go -package=model
//

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	consensus "github.com/0xsoniclabs/daphne/daphne/consensus"
	gomock "go.uber.org/mock/gomock"
)

// MockDag is a mock of Dag interface.
type MockDag struct {
	ctrl     *gomock.Controller
	recorder *MockDagMockRecorder
	isgomock struct{}
}

// MockDagMockRecorder is the mock recorder for MockDag.
type MockDagMockRecorder struct {
	mock *MockDag
}

// NewMockDag creates a new mock instance.
func NewMockDag(ctrl *gomock.Controller) *MockDag {
	mock := &MockDag{ctrl: ctrl}
	mock.recorder = &MockDagMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDag) EXPECT() *MockDagMockRecorder {
	return m.recorder
}

// AddEvent mocks base method.
func (m *MockDag) AddEvent(eventMessage EventMessage) []*Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddEvent", eventMessage)
	ret0, _ := ret[0].([]*Event)
	return ret0
}

// AddEvent indicates an expected call of AddEvent.
func (mr *MockDagMockRecorder) AddEvent(eventMessage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddEvent", reflect.TypeOf((*MockDag)(nil).AddEvent), eventMessage)
}

// GetHeads mocks base method.
func (m *MockDag) GetHeads() map[consensus.ValidatorId]*Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeads")
	ret0, _ := ret[0].(map[consensus.ValidatorId]*Event)
	return ret0
}

// GetHeads indicates an expected call of GetHeads.
func (mr *MockDagMockRecorder) GetHeads() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeads", reflect.TypeOf((*MockDag)(nil).GetHeads))
}
