// Code generated by MockGen. DO NOT EDIT.
// Source: event.go
//
// Generated by this command:
//
//	mockgen -source event.go -destination=event_mock.go -package=model
//

// Package model is a generated GoMock package.
package model

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventVisitor is a mock of EventVisitor interface.
type MockEventVisitor struct {
	ctrl     *gomock.Controller
	recorder *MockEventVisitorMockRecorder
	isgomock struct{}
}

// MockEventVisitorMockRecorder is the mock recorder for MockEventVisitor.
type MockEventVisitorMockRecorder struct {
	mock *MockEventVisitor
}

// NewMockEventVisitor creates a new mock instance.
func NewMockEventVisitor(ctrl *gomock.Controller) *MockEventVisitor {
	mock := &MockEventVisitor{ctrl: ctrl}
	mock.recorder = &MockEventVisitorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventVisitor) EXPECT() *MockEventVisitorMockRecorder {
	return m.recorder
}

// Visit mocks base method.
func (m *MockEventVisitor) Visit(event *Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Visit", event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Visit indicates an expected call of Visit.
func (mr *MockEventVisitorMockRecorder) Visit(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Visit", reflect.TypeOf((*MockEventVisitor)(nil).Visit), event)
}
