// Code generated by "stringer -type=VisitResult -output event_visitor_string.go -trimprefix Visit_"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Visit_Descent-0]
	_ = x[Visit_Prune-1]
	_ = x[Visit_Abort-2]
}

const _VisitResult_name = "DescentPruneAbort"

var _VisitResult_index = [...]uint8{0, 7, 12, 17}

func (i VisitResult) String() string {
	if i >= VisitResult(len(_VisitResult_index)-1) {
		return "VisitResult(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _VisitResult_name[_VisitResult_index[i]:_VisitResult_index[i+1]]
}
