// Code generated by MockGen. DO NOT EDIT.
// Source: layering.go
//
// Generated by this command:
//
//	mockgen -source layering.go -destination=layering_mock.go -package=layering
//

// Package layering is a generated GoMock package.
package layering

import (
	reflect "reflect"

	consensus "github.com/0xsoniclabs/daphne/daphne/consensus"
	model "github.com/0xsoniclabs/daphne/daphne/consensus/dag/model"
	gomock "go.uber.org/mock/gomock"
)

// MockLayering is a mock of Layering interface.
type MockLayering struct {
	ctrl     *gomock.Controller
	recorder *MockLayeringMockRecorder
	isgomock struct{}
}

// MockLayeringMockRecorder is the mock recorder for MockLayering.
type MockLayeringMockRecorder struct {
	mock *MockLayering
}

// NewMockLayering creates a new mock instance.
func NewMockLayering(ctrl *gomock.Controller) *MockLayering {
	mock := &MockLayering{ctrl: ctrl}
	mock.recorder = &MockLayeringMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLayering) EXPECT() *MockLayeringMockRecorder {
	return m.recorder
}

// IsCandidate mocks base method.
func (m *MockLayering) IsCandidate(dag *model.Dag, event *model.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsCandidate", dag, event)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsCandidate indicates an expected call of IsCandidate.
func (mr *MockLayeringMockRecorder) IsCandidate(dag, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsCandidate", reflect.TypeOf((*MockLayering)(nil).IsCandidate), dag, event)
}

// IsLeader mocks base method.
func (m *MockLayering) IsLeader(dag *model.Dag, event *model.Event) Verdict {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLeader", dag, event)
	ret0, _ := ret[0].(Verdict)
	return ret0
}

// IsLeader indicates an expected call of IsLeader.
func (mr *MockLayeringMockRecorder) IsLeader(dag, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLeader", reflect.TypeOf((*MockLayering)(nil).IsLeader), dag, event)
}

// SortLeaders mocks base method.
func (m *MockLayering) SortLeaders(dag *model.Dag, events []*model.Event) []*model.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SortLeaders", dag, events)
	ret0, _ := ret[0].([]*model.Event)
	return ret0
}

// SortLeaders indicates an expected call of SortLeaders.
func (mr *MockLayeringMockRecorder) SortLeaders(dag, events any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SortLeaders", reflect.TypeOf((*MockLayering)(nil).SortLeaders), dag, events)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewLayering mocks base method.
func (m *MockFactory) NewLayering(committee *consensus.Committee) Layering {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewLayering", committee)
	ret0, _ := ret[0].(Layering)
	return ret0
}

// NewLayering indicates an expected call of NewLayering.
func (mr *MockFactoryMockRecorder) NewLayering(committee any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewLayering", reflect.TypeOf((*MockFactory)(nil).NewLayering), committee)
}
