// Code generated by MockGen. DO NOT EDIT.
// Source: condition.go
//
// Generated by this command:
//
//	mockgen -source condition.go -destination=condition_mock.go -package=emitter
//

// Package emitter is a generated GoMock package.
package emitter

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCondition is a mock of Condition interface.
type MockCondition struct {
	ctrl     *gomock.Controller
	recorder *MockConditionMockRecorder
	isgomock struct{}
}

// MockConditionMockRecorder is the mock recorder for MockCondition.
type MockConditionMockRecorder struct {
	mock *MockCondition
}

// NewMockCondition creates a new mock instance.
func NewMockCondition(ctrl *gomock.Controller) *MockCondition {
	mock := &MockCondition{ctrl: ctrl}
	mock.recorder = &MockConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCondition) EXPECT() *MockConditionMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockCondition) Evaluate(emitter *Emitter) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", emitter)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockConditionMockRecorder) Evaluate(emitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockCondition)(nil).Evaluate), emitter)
}

// Reset mocks base method.
func (m *MockCondition) Reset(emitter *Emitter) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset", emitter)
}

// Reset indicates an expected call of Reset.
func (mr *MockConditionMockRecorder) Reset(emitter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockCondition)(nil).Reset), emitter)
}
