// Code generated by MockGen. DO NOT EDIT.
// Source: emitter.go
//
// Generated by this command:
//
//	mockgen -source emitter.go -destination=emitter_mock.go -package=emitter
//

// Package emitter is a generated GoMock package.
package emitter

import (
	reflect "reflect"

	model "github.com/0xsoniclabs/daphne/daphne/consensus/dag/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockChannel) Emit(parents []model.EventId) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", parents)
}

// Emit indicates an expected call of Emit.
func (mr *MockChannelMockRecorder) Emit(parents any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockChannel)(nil).Emit), parents)
}
