// Code generated by MockGen. DO NOT EDIT.
// Source: emitter.go
//
// Generated by this command:
//
//	mockgen -source emitter.go -destination=emitter_mock.go -package=emitter
//

// Package emitter is a generated GoMock package.
package emitter

import (
	reflect "reflect"

	consensus "github.com/0xsoniclabs/daphne/daphne/consensus"
	model "github.com/0xsoniclabs/daphne/daphne/consensus/dag/model"
	gomock "go.uber.org/mock/gomock"
)

// MockChannel is a mock of Channel interface.
type MockChannel struct {
	ctrl     *gomock.Controller
	recorder *MockChannelMockRecorder
	isgomock struct{}
}

// MockChannelMockRecorder is the mock recorder for MockChannel.
type MockChannelMockRecorder struct {
	mock *MockChannel
}

// NewMockChannel creates a new mock instance.
func NewMockChannel(ctrl *gomock.Controller) *MockChannel {
	mock := &MockChannel{ctrl: ctrl}
	mock.recorder = &MockChannelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannel) EXPECT() *MockChannelMockRecorder {
	return m.recorder
}

// Emit mocks base method.
func (m *MockChannel) Emit(dagSnapshot map[consensus.ValidatorId]*model.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Emit", dagSnapshot)
}

// Emit indicates an expected call of Emit.
func (mr *MockChannelMockRecorder) Emit(dagSnapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Emit", reflect.TypeOf((*MockChannel)(nil).Emit), dagSnapshot)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
	isgomock struct{}
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewEmitter mocks base method.
func (m *MockFactory) NewEmitter(arg0 Channel, arg1 model.Dag, arg2 consensus.ValidatorId) Emitter {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewEmitter", arg0, arg1, arg2)
	ret0, _ := ret[0].(Emitter)
	return ret0
}

// NewEmitter indicates an expected call of NewEmitter.
func (mr *MockFactoryMockRecorder) NewEmitter(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewEmitter", reflect.TypeOf((*MockFactory)(nil).NewEmitter), arg0, arg1, arg2)
}

// String mocks base method.
func (m *MockFactory) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockFactoryMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockFactory)(nil).String))
}

// MockEmitter is a mock of Emitter interface.
type MockEmitter struct {
	ctrl     *gomock.Controller
	recorder *MockEmitterMockRecorder
	isgomock struct{}
}

// MockEmitterMockRecorder is the mock recorder for MockEmitter.
type MockEmitterMockRecorder struct {
	mock *MockEmitter
}

// NewMockEmitter creates a new mock instance.
func NewMockEmitter(ctrl *gomock.Controller) *MockEmitter {
	mock := &MockEmitter{ctrl: ctrl}
	mock.recorder = &MockEmitterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmitter) EXPECT() *MockEmitterMockRecorder {
	return m.recorder
}

// OnChange mocks base method.
func (m *MockEmitter) OnChange() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnChange")
}

// OnChange indicates an expected call of OnChange.
func (mr *MockEmitterMockRecorder) OnChange() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnChange", reflect.TypeOf((*MockEmitter)(nil).OnChange))
}

// Stop mocks base method.
func (m *MockEmitter) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockEmitterMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockEmitter)(nil).Stop))
}
