// Code generated by MockGen. DO NOT EDIT.
// Source: state_delay_model.go
//
// Generated by this command:
//
//	mockgen -source state_delay_model.go -destination=state_delay_model_mock.go -package=state
//

// Package state is a generated GoMock package.
package state

import (
	reflect "reflect"
	time "time"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessingDelayModel is a mock of ProcessingDelayModel interface.
type MockProcessingDelayModel struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingDelayModelMockRecorder
	isgomock struct{}
}

// MockProcessingDelayModelMockRecorder is the mock recorder for MockProcessingDelayModel.
type MockProcessingDelayModelMockRecorder struct {
	mock *MockProcessingDelayModel
}

// NewMockProcessingDelayModel creates a new mock instance.
func NewMockProcessingDelayModel(ctrl *gomock.Controller) *MockProcessingDelayModel {
	mock := &MockProcessingDelayModel{ctrl: ctrl}
	mock.recorder = &MockProcessingDelayModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessingDelayModel) EXPECT() *MockProcessingDelayModelMockRecorder {
	return m.recorder
}

// GetBlockFinalizationDelay mocks base method.
func (m *MockProcessingDelayModel) GetBlockFinalizationDelay(blockNumber uint32) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBlockFinalizationDelay", blockNumber)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetBlockFinalizationDelay indicates an expected call of GetBlockFinalizationDelay.
func (mr *MockProcessingDelayModelMockRecorder) GetBlockFinalizationDelay(blockNumber any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBlockFinalizationDelay", reflect.TypeOf((*MockProcessingDelayModel)(nil).GetBlockFinalizationDelay), blockNumber)
}

// GetTransactionDelay mocks base method.
func (m *MockProcessingDelayModel) GetTransactionDelay(tx types.Transaction) time.Duration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionDelay", tx)
	ret0, _ := ret[0].(time.Duration)
	return ret0
}

// GetTransactionDelay indicates an expected call of GetTransactionDelay.
func (mr *MockProcessingDelayModelMockRecorder) GetTransactionDelay(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionDelay", reflect.TypeOf((*MockProcessingDelayModel)(nil).GetTransactionDelay), tx)
}
