// Code generated by MockGen. DO NOT EDIT.
// Source: state.go
//
// Generated by this command:
//
//	mockgen -source state.go -destination=state_mock.go -package=state
//

// Package state is a generated GoMock package.
package state

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockState is a mock of State interface.
type MockState struct {
	ctrl     *gomock.Controller
	recorder *MockStateMockRecorder
	isgomock struct{}
}

// MockStateMockRecorder is the mock recorder for MockState.
type MockStateMockRecorder struct {
	mock *MockState
}

// NewMockState creates a new mock instance.
func NewMockState(ctrl *gomock.Controller) *MockState {
	mock := &MockState{ctrl: ctrl}
	mock.recorder = &MockStateMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockState) EXPECT() *MockStateMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockState) Apply(transactions []types.Transaction) types.Block {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", transactions)
	ret0, _ := ret[0].(types.Block)
	return ret0
}

// Apply indicates an expected call of Apply.
func (mr *MockStateMockRecorder) Apply(transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockState)(nil).Apply), transactions)
}

// GetAccount mocks base method.
func (m *MockState) GetAccount(address types.Address) Account {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccount", address)
	ret0, _ := ret[0].(Account)
	return ret0
}

// GetAccount indicates an expected call of GetAccount.
func (mr *MockStateMockRecorder) GetAccount(address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccount", reflect.TypeOf((*MockState)(nil).GetAccount), address)
}

// GetCurrentBlockNumber mocks base method.
func (m *MockState) GetCurrentBlockNumber() uint32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentBlockNumber")
	ret0, _ := ret[0].(uint32)
	return ret0
}

// GetCurrentBlockNumber indicates an expected call of GetCurrentBlockNumber.
func (mr *MockStateMockRecorder) GetCurrentBlockNumber() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentBlockNumber", reflect.TypeOf((*MockState)(nil).GetCurrentBlockNumber))
}
