// Code generated by MockGen. DO NOT EDIT.
// Source: scenario.go
//
// Generated by this command:
//
//	mockgen -source scenario.go -destination=scenario_mock.go -package=scenario
//

// Package scenario is a generated GoMock package.
package scenario

import (
	reflect "reflect"

	tracker "github.com/0xsoniclabs/daphne/daphne/tracker"
	gomock "go.uber.org/mock/gomock"
)

// MockScenario is a mock of Scenario interface.
type MockScenario struct {
	ctrl     *gomock.Controller
	recorder *MockScenarioMockRecorder
	isgomock struct{}
}

// MockScenarioMockRecorder is the mock recorder for MockScenario.
type MockScenarioMockRecorder struct {
	mock *MockScenario
}

// NewMockScenario creates a new mock instance.
func NewMockScenario(ctrl *gomock.Controller) *MockScenario {
	mock := &MockScenario{ctrl: ctrl}
	mock.recorder = &MockScenarioMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScenario) EXPECT() *MockScenarioMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *MockScenario) Run(arg0 Logger, arg1 tracker.Tracker) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockScenarioMockRecorder) Run(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockScenario)(nil).Run), arg0, arg1)
}
