// Code generated by MockGen. DO NOT EDIT.
// Source: export.go
//
// Generated by this command:
//
//	mockgen -source export.go -destination=export_mock.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mock_Writer is a mock of _Writer interface.
type Mock_Writer struct {
	ctrl     *gomock.Controller
	recorder *Mock_WriterMockRecorder
	isgomock struct{}
}

// Mock_WriterMockRecorder is the mock recorder for Mock_Writer.
type Mock_WriterMockRecorder struct {
	mock *Mock_Writer
}

// NewMock_Writer creates a new mock instance.
func NewMock_Writer(ctrl *gomock.Controller) *Mock_Writer {
	mock := &Mock_Writer{ctrl: ctrl}
	mock.recorder = &Mock_WriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_Writer) EXPECT() *Mock_WriterMockRecorder {
	return m.recorder
}

// Write mocks base method.
func (m *Mock_Writer) Write(p []byte) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Write", p)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Write indicates an expected call of Write.
func (mr *Mock_WriterMockRecorder) Write(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*Mock_Writer)(nil).Write), p)
}
