// Code generated by MockGen. DO NOT EDIT.
// Source: parquet.go
//
// Generated by this command:
//
//	mockgen -source parquet.go -destination=parquet_mock.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mock_sinkTarget is a mock of _sinkTarget interface.
type Mock_sinkTarget struct {
	ctrl     *gomock.Controller
	recorder *Mock_sinkTargetMockRecorder
	isgomock struct{}
}

// Mock_sinkTargetMockRecorder is the mock recorder for Mock_sinkTarget.
type Mock_sinkTargetMockRecorder struct {
	mock *Mock_sinkTarget
}

// NewMock_sinkTarget creates a new mock instance.
func NewMock_sinkTarget(ctrl *gomock.Controller) *Mock_sinkTarget {
	mock := &Mock_sinkTarget{ctrl: ctrl}
	mock.recorder = &Mock_sinkTargetMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mock_sinkTarget) EXPECT() *Mock_sinkTargetMockRecorder {
	return m.recorder
}

// append mocks base method.
func (m *Mock_sinkTarget) append(entry *Entry) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "append", entry)
	ret0, _ := ret[0].(error)
	return ret0
}

// append indicates an expected call of append.
func (mr *Mock_sinkTargetMockRecorder) append(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "append", reflect.TypeOf((*Mock_sinkTarget)(nil).append), entry)
}

// close mocks base method.
func (m *Mock_sinkTarget) close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "close")
	ret0, _ := ret[0].(error)
	return ret0
}

// close indicates an expected call of close.
func (mr *Mock_sinkTargetMockRecorder) close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "close", reflect.TypeOf((*Mock_sinkTarget)(nil).close))
}
