// Code generated by MockGen. DO NOT EDIT.
// Source: tracker.go
//
// Generated by this command:
//
//	mockgen -source tracker.go -destination=tracker_mock.go -package=tracker
//

// Package tracker is a generated GoMock package.
package tracker

import (
	reflect "reflect"

	mark "github.com/0xsoniclabs/daphne/daphne/tracker/mark"
	gomock "go.uber.org/mock/gomock"
)

// MockTracker is a mock of Tracker interface.
type MockTracker struct {
	ctrl     *gomock.Controller
	recorder *MockTrackerMockRecorder
	isgomock struct{}
}

// MockTrackerMockRecorder is the mock recorder for MockTracker.
type MockTrackerMockRecorder struct {
	mock *MockTracker
}

// NewMockTracker creates a new mock instance.
func NewMockTracker(ctrl *gomock.Controller) *MockTracker {
	mock := &MockTracker{ctrl: ctrl}
	mock.recorder = &MockTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracker) EXPECT() *MockTrackerMockRecorder {
	return m.recorder
}

// Track mocks base method.
func (m *MockTracker) Track(arg0 mark.Mark, meta ...any) {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range meta {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Track", varargs...)
}

// Track indicates an expected call of Track.
func (mr *MockTrackerMockRecorder) Track(arg0 any, meta ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, meta...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Track", reflect.TypeOf((*MockTracker)(nil).Track), varargs...)
}

// With mocks base method.
func (m *MockTracker) With(meta ...any) Tracker {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range meta {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "With", varargs...)
	ret0, _ := ret[0].(Tracker)
	return ret0
}

// With indicates an expected call of With.
func (mr *MockTrackerMockRecorder) With(meta ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "With", reflect.TypeOf((*MockTracker)(nil).With), meta...)
}

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Append mocks base method.
func (m *MockSink) Append(entry *Entry) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Append", entry)
}

// Append indicates an expected call of Append.
func (mr *MockSinkMockRecorder) Append(entry any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Append", reflect.TypeOf((*MockSink)(nil).Append), entry)
}

// Close mocks base method.
func (m *MockSink) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSinkMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSink)(nil).Close))
}
