// Code generated by MockGen. DO NOT EDIT.
// Source: rpc.go
//
// Generated by this command:
//
//	mockgen -source rpc.go -destination=rpc_mock.go -package=rpc
//

// Package rpc is a generated GoMock package.
package rpc

import (
	reflect "reflect"

	types "github.com/0xsoniclabs/daphne/daphne/types"
	gomock "go.uber.org/mock/gomock"
)

// MockServer is a mock of Server interface.
type MockServer struct {
	ctrl     *gomock.Controller
	recorder *MockServerMockRecorder
	isgomock struct{}
}

// MockServerMockRecorder is the mock recorder for MockServer.
type MockServerMockRecorder struct {
	mock *MockServer
}

// NewMockServer creates a new mock instance.
func NewMockServer(ctrl *gomock.Controller) *MockServer {
	mock := &MockServer{ctrl: ctrl}
	mock.recorder = &MockServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServer) EXPECT() *MockServerMockRecorder {
	return m.recorder
}

// GetReceipt mocks base method.
func (m *MockServer) GetReceipt(hash types.Hash) (types.Receipt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipt", hash)
	ret0, _ := ret[0].(types.Receipt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceipt indicates an expected call of GetReceipt.
func (mr *MockServerMockRecorder) GetReceipt(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipt", reflect.TypeOf((*MockServer)(nil).GetReceipt), hash)
}

// IsPending mocks base method.
func (m *MockServer) IsPending(hash types.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsPending", hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsPending indicates an expected call of IsPending.
func (mr *MockServerMockRecorder) IsPending(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsPending", reflect.TypeOf((*MockServer)(nil).IsPending), hash)
}

// Send mocks base method.
func (m *MockServer) Send(tx types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockServerMockRecorder) Send(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockServer)(nil).Send), tx)
}

// MockBackend is a mock of Backend interface.
type MockBackend struct {
	ctrl     *gomock.Controller
	recorder *MockBackendMockRecorder
	isgomock struct{}
}

// MockBackendMockRecorder is the mock recorder for MockBackend.
type MockBackendMockRecorder struct {
	mock *MockBackend
}

// NewMockBackend creates a new mock instance.
func NewMockBackend(ctrl *gomock.Controller) *MockBackend {
	mock := &MockBackend{ctrl: ctrl}
	mock.recorder = &MockBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBackend) EXPECT() *MockBackendMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBackend) Add(tx types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBackendMockRecorder) Add(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBackend)(nil).Add), tx)
}

// Contains mocks base method.
func (m *MockBackend) Contains(hash types.Hash) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Contains", hash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Contains indicates an expected call of Contains.
func (mr *MockBackendMockRecorder) Contains(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Contains", reflect.TypeOf((*MockBackend)(nil).Contains), hash)
}

// GetReceipt mocks base method.
func (m *MockBackend) GetReceipt(hash types.Hash) (types.Receipt, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipt", hash)
	ret0, _ := ret[0].(types.Receipt)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetReceipt indicates an expected call of GetReceipt.
func (mr *MockBackendMockRecorder) GetReceipt(hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipt", reflect.TypeOf((*MockBackend)(nil).GetReceipt), hash)
}
