name: Check Build

on:
    push:

jobs:
    check-build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Golang dependency
              uses: actions/setup-go@v3
              with:
                    go-version: '1.24'

            - name: Test
              run: go test ./... -count 1 -coverpkg=./... -coverprofile=coverage.cov

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                files: coverage.cov
                fail_ci_if_error: true
                verbose: true